apiVersion: v1
kind: Service
metadata:
    name: "o2aks-5544"
    labels:
        app: "o2aks-5544"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "o2aks-5544"